### ISSUE TITLE
0.3.1 Release

### ISSUE THREAD

**Issue by petems** [voxpupuli/puppet-ghost#25]
@andschwa Can you do a 0.3.1 release? Forgot to update the docs :+1:

**Comment by petems** [comment]
Actually, found a few issues (include_nodejs vs manage_nodejs), need to fix before we can release :+1:

**Comment by andschwa** [comment]
:+1: Let me know when :smile:

**Comment by andschwa** [comment]
Did you manage to sort those issues out? I can take a look if need be.

**Comment by petems** [comment]
Sure, the main one is that `$::ghost::manage_nodejs` on https://github.com/andschwa/puppet-ghost/blob/master/manifests/setup.pp needs to be changed to `$::ghost::include_nodejs` :+1:

**Comment by petems** [comment]
See https://github.com/andschwa/puppet-ghost/pull/29

**Comment by andschwa** [comment]
Awesome! Sorry about forgetting before :)

**Comment by andschwa** [comment]
I'll update the Forge in a minute here.

**Comment by andschwa** [comment]
Actually I'm going to see if I can use Docker to smoke test this before I publish it. @petems if you've used it before and have any tips (on Docker or testing the latest version of this module) let me know!

**Comment by andschwa** [comment]
Hey @petems: I think I'll change blog::socket to be false by default, as that's how Ghost runs by default. It's one of those things where I set it to true because that's what I used, but probably shouldn't be the default.

**Comment by nibalizer** [comment]
I think we're into voxpupuli release territory here.

**Comment by andschwa** [comment]
Yes, closing this.
