### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by andschwa** [voxpupuli/puppet-ghost#27]
This module is apparently still in active use, but has quite a few issues that need fixing. I no longer use Puppet to manage my systems, and so it's a PITA to test. Hence I am looking for testers/maintainers/pull requests etc. PLEASE feel free to fix things and ping me to issue a release once it's tested.

**Comment by justin8** [comment]
I would do so, but every system I have is now systemd, and I don't use supervisord at all. I ended up writing my own ghost module to support ubuntu 15.04 and arch properly. I could probably try to merge them together, but it wouldn't be possible to have direct feature translation between supervisord and systemd without one of them ending up second class currently; or making a new backwards-incompatible version

**Comment by andschwa** [comment]
Pretty much everything has gone to systemd. I would support removing supervisord for systemd in a major version release.

**Comment by justin8** [comment]
Alright, I might look at merging them then next weekend if I get the time. Have business trips for the next month after that so hopefully I can fit it in.

**Comment by petems** [comment]
@justin8 I'd be interested in a systemd setup and adding tests and such :+1:

**Comment by justin8** [comment]
I've already got it going in a pure systemd implementation with some basic tests and such; it's the merging of the two that I haven't done. see: https://github.com/justin8/justin8-ghost (also on forge)

**Comment by andschwa** [comment]
I think pure systemd would probably be better than trying to leave a confusing pair of options between systemd and supervisord. If we can get systemd instead, that would be much better (and constitute a 0.4 release).

**Comment by justin8** [comment]
What would we do then to handle people using this module on older ubuntu versions? Just put a disclaimer saying it's not compatible?

Also, if following semantic versioning (as puppetlabs/forge suggest) it should probably be bumped to 1.x

**Comment by andschwa** [comment]
If they're using an older Ubuntu version then they can use an older module version just fine. I'm testing right now.

And you're right, it should probably be 1.0.0; that just feels so weird.

**Comment by justin8** [comment]
Haha, I know what you mean. I'm still kind of used to old-school versioning still where 1.x is 'stable' and so on. But semver does make much more sense when trying to compare actual versions.

If you're happy with that, we could probably just copy over the version I made with systemd support and call it andschwa/puppet-ghost v1.0.0

**Comment by andschwa** [comment]
@justin8 I'm still totally down for those changes. I don't use Puppet at all any more though, so I'm going to add you as a collaborator, and if you and @petems still use this, please feel free to change and tag a new release. I'll upload whatever you guys give me to the forge :fire:.

**Comment by justin8** [comment]
Sure, I'll take a look when I get some time

**Comment by andschwa** [comment]
No problemo, definitely not under time constraints here :zzz: Do with it what you will!

**Comment by petems** [comment]
@andschwa Would you think about transfering the project to https://voxpupuli.org/? They take orphaned modules and integrated them with community plumbing such as testing and clearing out old and new PR's and issues.

**Comment by andschwa** [comment]
Yes, I love that idea. I'll try to take care of that today.

**Comment by andschwa** [comment]
@petems are you one of the administrators of Vox Pupuli? I need to be added to the modules/admin team to transfer this repo.

I'd be happy to transfer all of my released modules:

**Comment by petems** [comment]
@andschwa I'm just a collaborator, not an admin. I'll see if I can find someone to help out on IRC! :smile: 
There's already a voxpupuli unattended upgrades, so I'm not sure if they'll take that one: https://forge.puppetlabs.com/puppet/unattended_upgrades

The others I think should be ok, especially ghost! :smile:

**Comment by nibalizer** [comment]
hi @andschwa I'm happy to help you do this. Do you use IRC? being in #voxpupuli on freenode helps this process out a bunch. I think we don't waant to move unaattended_upgrades since I think there are like 9 of these out there, hopefully one day we can converge them all.

Why is the module agpl? Would the contributors be willing to entertain a re license to Apache 2.0? That is not a requirement for joining VoxPupuli, i just have very little agpl experience, especially for what it means for a puppet server.

**Comment by daenney** [comment]
> I think we don't waant to move unaattended_upgrades since I think there are like 9 of these out there, hopefully one day we can converge them all.

We already have one https://github.com/voxpupuli/puppet-unattended_upgrades :wink:.

**Comment by andschwa** [comment]
I have no clue why anyone uses my unattended_upgrades module... the readme straight up says it's redundant. SIgned onto #voxpupuli.

It's AGPL just because that's my go-to license. I'd be okay relicensing, and I'm sure @petems would be too. That just leaves @andrew-timmes.

**Comment by andschwa** [comment]
Not relicensing for now, transferring to Vox Pupuli.

**Comment by andschwa** [comment]
I found maintainers! :smile:
